import {Unit} from "./data";
import {SPECIALS} from "./specials";

export const CONFLUX: Unit[] = [{
  id: 'SPRITES',
  attack: 2,
  defence: 0,
  health: 2,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [2,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'SPRITES_#PACK',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "SPRITES",
  costs: [4,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'STORM_ELEMENTALS',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'STORM_ELEMENTALS_#PACK',
  attack: 2,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: true,
  special: [],
  upgradeFrom: "STORM_ELEMENTALS",
  costs: [5,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'ICE_ELEMENTALS',
  attack: 2,
  defence: 1,
  health: 4,
  initiative: 5,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'ICE_ELEMENTALS_#PACK',
  attack: 3,
  defence: 1,
  health: 5,
  initiative: 6,
  ranged: true,
  special: [],
  upgradeFrom: "ICE_ELEMENTALS",
  costs: [7,0],
  faction: "Conflux",
  tier: "Bronze"
},{
  id: 'ENERGY_ELEMENTALS',
  attack: 3,
  defence: 1,
  health: 5,
  initiative: 5,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Conflux",
  tier: "Silver"
},{
  id: 'ENERGY_ELEMENTALS_#PACK',
  attack: 4,
  defence: 1,
  health: 6,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "ENERGY_ELEMENTALS",
  costs: [8,0],
  faction: "Conflux",
  tier: "Silver"
},{
  id: 'MAGMA_ELEMENTALS',
  attack: 4,
  defence: 2,
  health: 6,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [9,0],
  faction: "Conflux",
  tier: "Silver"
},{
  id: 'MAGMA_ELEMENTALS_#PACK',
  attack: 5,
  defence: 2,
  health: 6,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "MAGMA_ELEMENTALS",
  costs: [13,0],
  faction: "Conflux",
  tier: "Silver"
},{
  id: 'MAGIC_ELEMENTALS',
  attack: 5,
  defence: 2,
  health: 7,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Conflux",
  tier: "Gold"
},{
  id: 'MAGIC_ELEMENTALS_#PACK',
  attack: 6,
  defence: 2,
  health: 8,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC],
  upgradeFrom: "MAGIC_ELEMENTALS",
  costs: [18,1],
  faction: "Conflux",
  tier: "Gold"
},{
  id: 'PHOENIXES',
  attack: 6,
  defence: 2,
  health: 7,
  initiative: 12,
  ranged: false,
  special: [SPECIALS.REBIRTH],
  upgradeFrom: "",
  costs: [21,1],
  faction: "Conflux",
  tier: "Gold"
},{
  id: 'PHOENIXES_#PACK',
  attack: 7,
  defence: 2,
  health: 9,
  initiative: 18,
  ranged: false,
  special: [],
  upgradeFrom: "PHOENIXES",
  costs: [27,2],
  faction: "Conflux",
  tier: "Gold"
}]
