import {Unit} from "./data";
import {SPECIALS} from "./specials";

export const COVE: Unit[] = [{
  id: 'OCEANIDS',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [2,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'OCEANIDS_#PACK',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "OCEANIDS",
  costs: [3,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'SEAMEN',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 5,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'SEAMEN_#PACK',
  attack: 2,
  defence: 1,
  health: 5,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "SEAMEN",
  costs: [5,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'SEA_DOGS',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'SEA_DOGS_#PACK',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT, SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "SEA_DOGS",
  costs: [6,0],
  faction: "Cove",
  tier: "Bronze"
},{
  id: 'AYSSIDS',
  attack: 3,
  defence: 1,
  health: 5,
  initiative: 9,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Cove",
  tier: "Silver"
},{
  id: 'AYSSIDS_#PACK',
  attack: 3,
  defence: 1,
  health: 6,
  initiative: 11,
  ranged: false,
  special: [],
  upgradeFrom: "AYSSIDS",
  costs: [10,0],
  faction: "Cove",
  tier: "Silver"
},{
  id: 'SORCERESSES',
  attack: 4,
  defence: 1,
  health: 5,
  initiative: 6,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [8,0],
  faction: "Cove",
  tier: "Silver"
},{
  id: 'SORCERESSES_#PACK',
  attack: 5,
  defence: 1,
  health: 6,
  initiative: 7,
  ranged: true,
  special: [SPECIALS.WEAKNESS_ON_ATTACK],
  upgradeFrom: "SORCERESSES",
  costs: [13,0],
  faction: "Cove",
  tier: "Silver"
},{
  id: 'NIX',
  attack: 5,
  defence: 2,
  health: 7,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Cove",
  tier: "Gold"
},{
  id: 'NIX_#PACK',
  attack: 6,
  defence: 2,
  health: 8,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.LIMIT_DAMAGE_FROM_ATTACK],
  upgradeFrom: "NIX",
  costs: [20,1],
  faction: "Cove",
  tier: "Gold"
},{
  id: 'HASPIDS',
  attack: 5,
  defence: 3,
  health: 7,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.REVENGE],
  upgradeFrom: "",
  costs: [18,1],
  faction: "Cove",
  tier: "Gold"
},{
  id: 'HASPIDS_#PACK',
  attack: 6,
  defence: 3,
  health: 9,
  initiative: 12,
  ranged: false,
  special: [SPECIALS.MIGHTY_POISON],
  upgradeFrom: "HASPIDS",
  costs: [32,2],
  faction: "Cove",
  tier: "Gold"
}]
