import { Unit } from "./data";
import { SPECIALS } from "./specials";


export const DUNGEON: Unit[] = [{
  id: 'TROGLODYTES',
  attack: 2,
  defence: 1,
  health: 2,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [2,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'TROGLODYTES_#PACK',
  attack: 3,
  defence: 1,
  health: 2,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.IGNORE_PARALYSIS],
  upgradeFrom: "TROGLODYTES",
  costs: [3,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'HARPIES',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'HARPIES_#PACK',
  attack: 3,
  defence: 0,
  health: 3,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "HARPIES",
  costs: [5,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'EVIL_EYES',
  attack: 3,
  defence: 0,
  health: 3,
  initiative: 5,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'EVIL_EYES_#PACK',
  attack: 3,
  defence: 1,
  health: 3,
  initiative: 7,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT],
  upgradeFrom: "EVIL_EYES",
  costs: [6,0],
  faction: "Dungeon",
  tier: "Bronze"
},{
  id: 'MEDUSAS',
  attack: 3,
  defence: 1,
  health: 4,
  initiative: 5,
  ranged: true,
  special: [SPECIALS.CHANCE_TO_PARALYZE_ON_RETALIATION],
  upgradeFrom: "",
  costs: [6,0],
  faction: "Dungeon",
  tier: "Silver"
},{
  id: 'MEDUSAS_#PACK',
  attack: 4,
  defence: 1,
  health: 4,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.PARALYZE_ON_RETALIATION, SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT],
  upgradeFrom: "MEDUSAS",
  costs: [12,0],
  faction: "Dungeon",
  tier: "Silver"
},{
  id: 'MINOTAURS',
  attack: 4,
  defence: 2,
  health: 4,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [8,0],
  faction: "Dungeon",
  tier: "Silver"
},{
  id: 'MINOTAURS_#PACK',
  attack: 5,
  defence: 2,
  health: 4,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "MINOTAURS",
  costs: [14,0],
  faction: "Dungeon",
  tier: "Silver"
},{
  id: 'MANTICORES',
  attack: 5,
  defence: 1,
  health: 6,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [10,0],
  faction: "Dungeon",
  tier: "Gold"
},{
  id: 'MANTICORES_#PACK',
  attack: 5,
  defence: 1,
  health: 6,
  initiative: 11,
  ranged: false,
  special: [SPECIALS.IGNORE_DEFENCE],
  upgradeFrom: "MANTICORES",
  costs: [18,1],
  faction: "Dungeon",
  tier: "Gold"
},{
  id: 'BLACK_DRAGONS',
  attack: 6,
  defence: 3,
  health: 8,
  initiative: 11,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [19,1],
  faction: "Dungeon",
  tier: "Gold"
},{
  id: 'BLACK_DRAGONS_#PACK',
  attack: 8,
  defence: 3,
  health: 8,
  initiative: 15,
  ranged: false,
  special: [SPECIALS.IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC],
  upgradeFrom: "BLACK_DRAGONS",
  costs: [33,2],
  faction: "Dungeon",
  tier: "Gold"
}]
