import {Unit} from "./data";
import {SPECIALS} from "./specials";

export const NEUTRAL: Unit[] = [{
  id: 'AZURE_DRAGONS *',
  attack: 8,
  defence: 3,
  health: 10,
  initiative: 19,
  ranged: false,
  special: [SPECIALS.IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC, SPECIALS.FEAR],
  upgradeFrom: "",
  costs: [45,2],
  faction: "Neutral",
  tier: "Azure"
},{
  id: 'RUST_DRAGONS *',
  attack: 7,
  defence: 3,
  health: 10,
  initiative: 17,
  ranged: false,
  special: [SPECIALS.RUST_ATTACK],
  upgradeFrom: "",
  costs: [38,2],
  faction: "Neutral",
  tier: "Azure"
},{
  id: 'CRYSTAL_DRAGONS *',
  attack: 7,
  defence: 3,
  health: 9,
  initiative: 16,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [40,2],
  faction: "Neutral",
  tier: "Azure"
},{
  id: 'FAERIE_DRAGONS *',
  attack: 5,
  defence: 2,
  health: 8,
  initiative: 15,
  ranged: false,
  special: [SPECIALS.FAERIE_SPELL_ATTACK],
  upgradeFrom: "",
  costs: [35,2],
  faction: "Neutral",
  tier: "Azure"
},{
  id: 'TROLLS *',
  attack: 4,
  defence: 0,
  health: 7,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.HEAL_THREE_ON_ACTIVATION],
  upgradeFrom: "",
  costs: [13,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'GOLD_GOLEMS *',
  attack: 3,
  defence: 2,
  health: 6,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.SPELL_REDUCTION_TWO],
  upgradeFrom: "",
  costs: [14,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'DIAMOND_GOLEMS *',
  attack: 4,
  defence: 2,
  health: 6,
  initiative: 6,
  ranged: false,
  special: [SPECIALS.SPELL_REDUCTION_THREE],
  upgradeFrom: "",
  costs: [16,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'ENCHANTERS *',
  attack: 4,
  defence: 1,
  health: 5,
  initiative: 5,
  ranged: true,
  special: [SPECIALS.ENCHANTER],
  upgradeFrom: "",
  costs: [16,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'SHARPSHOOTER *',
  attack: 3,
  defence: 0,
  health: 6,
  initiative: 9,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY],
  upgradeFrom: "",
  costs: [10,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'NOMADS *',
  attack: 3,
  defence: 1,
  health: 4,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [10,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'MUMMIES *',
  attack: 3,
  defence: 1,
  health: 4,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.NO_ROLL_FOR_ATTACK, SPECIALS.CURSE],
  upgradeFrom: "",
  costs: [8,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'ROGUES *',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'BOARS *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'HALFLINGS *',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY, SPECIALS.LUCK],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'PEASANTS *',
  attack: 1,
  defence: 0,
  health: 3,
  initiative: 3,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'HALBERDIERS *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'MARKSMEN *',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 5,
  ranged: true,
  special: [SPECIALS.DOUBLE_ATTACK_NON_ADJACENT],
  upgradeFrom: "",
  costs: [7,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'GRIFFINS *',
  attack: 3,
  defence: 0,
  health: 4,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [7,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'ZEALOTS *',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 5,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'CRUSADERS *',
  attack: 3,
  defence: 2,
  health: 4,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.CRUSADERS_ATTACK],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'CHAMPIONS *',
  attack: 4,
  defence: 2,
  health: 6,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.ALWAYS_REROLL_MINUS_ONE, SPECIALS.CHAMPION_DOUBLE_ROLL],
  upgradeFrom: "",
  costs: [18,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'ARCHANGELS *',
  attack: 5,
  defence: 2,
  health: 7,
  initiative: 10,
  ranged: false,
  special: [SPECIALS.BONUS_AGAINST_ARCH_DEVIL],
  upgradeFrom: "",
  costs: [29,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'TROGLODYTES *',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 6,
  ranged: false,
  special: [SPECIALS.IGNORE_PARALYSIS],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'HARPIES *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'EVIL_EYES *',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT],
  upgradeFrom: "",
  costs: [6,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'MEDUSAS *',
  attack: 3,
  defence: 1,
  health: 4,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY_ADJACENT, SPECIALS.PARALYZE_ON_RETALIATION],
  upgradeFrom: "",
  costs: [11,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'MINOTAURUS *',
  attack: 3,
  defence: 2,
  health: 4,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.ATTACK_REROLL_MINUS_ONE],
  upgradeFrom: "",
  costs: [11,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'MANTICORE *',
  attack: 4,
  defence: 1,
  health: 7,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.DEFENCE_ON_ATTACK_ZERO_ONE],
  upgradeFrom: "",
  costs: [18,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'BLACK_DRAGON *',
  attack: 5,
  defence: 2,
  health: 7,
  initiative: 9,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [30,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'SKELETONS *',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'ZOMBIES *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 3,
  ranged: false,
  special: [SPECIALS.DEFENCE_ON_ATTACK_ZERO_ONE],
  upgradeFrom: "",
  costs: [5,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'WRAITHS *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.HEAL_TWO_ON_ACTIVATION],
  upgradeFrom: "",
  costs: [7,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'VAMPIRES *',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION, SPECIALS.HEAL_TWO_ON_ATTACK],
  upgradeFrom: "",
  costs: [9,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'LICHES *',
  attack: 3,
  defence: 0,
  health: 6,
  initiative: 7,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'DREAD_KNIGHTS *',
  attack: 5,
  defence: 1,
  health: 7,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.LOWER_RETALIATION_DAMAGE],
  upgradeFrom: "",
  costs: [18,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'GHOST_DRAGONS *',
  attack: 5,
  defence: 2,
  health: 6,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.CHANCE_MOVE_ENEMY_ON_ATTACK],
  upgradeFrom: "",
  costs: [28,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'GREMLINS *',
  attack: 2,
  defence: 0,
  health: 2,
  initiative: 5,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [2,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'GARGOYLES *',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.IGNORE_PARALYSIS],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'IRON_GOLEMS *',
  attack: 2,
  defence: 1,
  health: 4,
  initiative: 3,
  ranged: false,
  special: [SPECIALS.SPELL_REDUCTION_TWO],
  upgradeFrom: "",
  costs: [6,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'MAGI *',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY],
  upgradeFrom: "",
  costs: [11,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'GENIES *',
  attack: 3,
  defence: 1,
  health: 4,
  initiative: 9,
  ranged: false,
  special: [SPECIALS.BONUS_AGAINST_EFREET],
  upgradeFrom: "",
  costs: [11,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'NAGAS *',
  attack: 5,
  defence: 1,
  health: 6,
  initiative: 6,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "",
  costs: [16,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'TITANS *',
  attack: 6,
  defence: 2,
  health: 10,
  initiative: 10,
  ranged: true,
  special: [SPECIALS.IGNORE_COMBAT_PENALTY, SPECIALS.BONUS_AGAINST_BLACK_DRAGON],
  upgradeFrom: "",
  costs: [39,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'CENTAURS *',
  attack: 2,
  defence: 0,
  health: 5,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'DWARVES *',
  attack: 2,
  defence: 1,
  health: 4,
  initiative: 3,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'ELVES *',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 6,
  ranged: true,
  special: [SPECIALS.NOT_ADJACENT_CHANCE_DOUBLE_ATTACK],
  upgradeFrom: "",
  costs: [7,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'PEGASI *',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [14,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'DENDROIDS *',
  attack: 3,
  defence: 2,
  health: 6,
  initiative: 3,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'UNICORNS *',
  attack: 5,
  defence: 1,
  health: 7,
  initiative: 7,
  ranged: false,
  special: [SPECIALS.PARALYZE_ON_RETALIATION],
  upgradeFrom: "",
  costs: [18,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'GOLD_DRAGONS *',
  attack: 6,
  defence: 3,
  health: 9,
  initiative: 10,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [42,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'GNOLLS *',
  attack: 2,
  defence: 1,
  health: 2,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'LIZARDMEN *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 5,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'DRAGON_FLIES *',
  attack: 3,
  defence: 0,
  health: 3,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.LOWER_RETALIATION_DAMAGE],
  upgradeFrom: "",
  costs: [7,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'BASILISKS *',
  attack: 4,
  defence: 1,
  health: 4,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.CHANCE_TO_PARALYZE],
  upgradeFrom: "",
  costs: [12,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'GORGONS *',
  attack: 4,
  defence: 2,
  health: 4,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.DEATH_STARE],
  upgradeFrom: "",
  costs: [13,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'WYVERNS *',
  attack: 4,
  defence: 1,
  health: 7,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.CHANCE_TO_POISON],
  upgradeFrom: "",
  costs: [17,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'HYDRAS *',
  attack: 7,
  defence: 3,
  health: 8,
  initiative: 5,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "",
  costs: [40,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'FAMILIARS *',
  attack: 3,
  defence: 1,
  health: 2,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [6,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'MAGOGS *',
  attack: 2,
  defence: 0,
  health: 4,
  initiative: 6,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [8,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'CERBERI *',
  attack: 2,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: false,
  special: [SPECIALS.IGNORE_RETALIATION],
  upgradeFrom: "",
  costs: [10,0],
  faction: "Neutral",
  tier: "Bronze"
},{
  id: 'PIT_LORDS *',
  attack: 4,
  defence: 1,
  health: 5,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [15,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'DEMONS *',
  attack: 3,
  defence: 0,
  health: 8,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [13,0],
  faction: "Neutral",
  tier: "Silver"
},{
  id: 'EFREET *',
  attack: 4,
  defence: 2,
  health: 6,
  initiative: 13,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [20,0],
  faction: "Neutral",
  tier: "Gold"
},{
  id: 'ARCH_DEVILS *',
  attack: 5,
  defence: 2,
  health: 7,
  initiative: 10,
  ranged: false,
  special: [SPECIALS.BONUS_AGAINST_ARCH_ANGELS],
  upgradeFrom: "",
  costs: [23,0],
  faction: "Neutral",
  tier: "Gold"
}
// ,{
//   id: 'TEST *',
//   attack: 4,
//   defence: 1,
//   health: 5,
//   initiative: 7,
//   ranged: false,
//   special: [],
//   upgradeFrom: "",
//   costs: [2,0],
//   faction: "Test",
//   tier: "Test"
// }
]
