import {Unit} from "./data";
import {SPECIALS} from "./specials";

export const RAMPART: Unit[] = [{
  id: 'CENTAURS',
  attack: 2,
  defence: 0,
  health: 3,
  initiative: 6,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [2,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'CENTAURS_#PACK',
  attack: 3,
  defence: 0,
  health: 3,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "CENTAURS",
  costs: [3,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'DWARVES',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 3,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [3,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'DWARVES_#PACK',
  attack: 3,
  defence: 1,
  health: 3,
  initiative: 5,
  ranged: false,
  special: [],
  upgradeFrom: "DWARVES",
  costs: [4,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'ELVES',
  attack: 2,
  defence: 1,
  health: 3,
  initiative: 6,
  ranged: true,
  special: [],
  upgradeFrom: "",
  costs: [4,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'ELVES_#PACK',
  attack: 3,
  defence: 1,
  health: 3,
  initiative: 7,
  ranged: true,
  special: [SPECIALS.NOT_ADJACENT_CHANCE_DOUBLE_ATTACK],
  upgradeFrom: "ELVES",
  costs: [7,0],
  faction: "Rampart",
  tier: "Bronze"
},{
  id: 'PEGASI',
  attack: 3,
  defence: 0,
  health: 5,
  initiative: 8,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [6,0],
  faction: "Rampart",
  tier: "Silver"
},{
  id: 'PEGASI_#PACK',
  attack: 4,
  defence: 0,
  health: 6,
  initiative: 12,
  ranged: false,
  special: [],
  upgradeFrom: "PEGASI",
  costs: [10,0],
  faction: "Rampart",
  tier: "Silver"
},{
  id: 'DENDROIDS',
  attack: 4,
  defence: 2,
  health: 5,
  initiative: 3,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [8,0],
  faction: "Rampart",
  tier: "Silver"
},{
  id: 'DENDROIDS_#PACK',
  attack: 4,
  defence: 2,
  health: 6,
  initiative: 4,
  ranged: false,
  special: [],
  upgradeFrom: "DENDROIDS",
  costs: [15,0],
  faction: "Rampart",
  tier: "Silver"
},{
  id: 'UNICORNS',
  attack: 5,
  defence: 1,
  health: 8,
  initiative: 7,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [11,0],
  faction: "Rampart",
  tier: "Gold"
},{
  id: 'UNICORNS_#PACK',
  attack: 6,
  defence: 1,
  health: 8,
  initiative: 9,
  ranged: false,
  special: [],
  upgradeFrom: "UNICORNS",
  costs: [18,1],
  faction: "Rampart",
  tier: "Gold"
},{
  id: 'GOLD_DRAGONS',
  attack: 5,
  defence: 3,
  health: 9,
  initiative: 10,
  ranged: false,
  special: [],
  upgradeFrom: "",
  costs: [22,1],
  faction: "Rampart",
  tier: "Gold"
},{
  id: 'GOLD_DRAGONS_#PACK',
  attack: 6,
  defence: 3,
  health: 10,
  initiative: 16,
  ranged: false,
  special: [],
  upgradeFrom: "GOLD_DRAGONS",
  costs: [30,2],
  faction: "Rampart",
  tier: "Gold"
},]
