export enum SPECIALS {
  "IGNORE_RETALIATION",
  "IGNORE_COMBAT_PENALTY_ADJACENT",
  "IGNORE_COMBAT_PENALTY",
  "LUCK",
  "IGNORE_PARALYSIS",
  "CHANCE_TO_PARALYZE_ON_RETALIATION", // way to situational at the moment. perhaps set adjacency to false??
  "PARALYZE_ON_RETALIATION", // way to situational at the moment.perhaps set adjacency to false??
  "IGNORE_DEFENCE",
  "IGNORE_DAMAGE_FROM_SPECIALS_AND_MAGIC", // TODO !! Done but keep an eye out
  "DOUBLE_ATTACK_NON_ADJACENT",
  "REROLL_ZERO_ON_DICE",
  "REROLL_ON_OTHER_SPACE",
  "DEFENCE_ON_ATTACK_ONE",
  "DEFENCE_ON_ATTACK_ZERO_ONE",
  "HEAL_ONE_ON_ACTIVATION",
  "HEAL_TWO_ON_ACTIVATION",
  "HEAL_THREE_ON_ACTIVATION",
  "HEAL_TWO_ON_ATTACK",
  "RETALIATION_CURSE",
  "DEATH_BLOW",
  "ADD_ONE_TO_ATTACK_DICE",
  "FEAR",
  "NOT_ADJACENT_CHANCE_DOUBLE_ATTACK",
  "LOWER_RETALIATION_DAMAGE",
  "CHANCE_TO_PARALYZE_MINUS_ONE",
  "DEATH_STARE",
  "POISON",
  "MIGHTY_POISON",
  "RUST_ATTACK",
  "FAERIE_SPELL_ATTACK",
  "SPELL_REDUCTION_ONE", // TODO !! Done but keep an eye out
  "SPELL_REDUCTION_TWO", // TODO !! Done but keep an eye out
  "SPELL_REDUCTION_THREE", // TODO !! Done but keep an eye out
  "NO_ROLL_FOR_ATTACK",
  "CURSE",
  "ENCHANTER",
  "CRUSADERS_ATTACK",
  "CHAMPION_DOUBLE_ROLL",
  "ALWAYS_REROLL_MINUS_ONE",
  "ATTACK_REROLL_MINUS_ONE",
  "BONUS_AGAINST_ARCH_DEVIL",
  "BONUS_AGAINST_EFREET",
  "BONUS_AGAINST_BLACK_DRAGON",
  "BONUS_AGAINST_ARCH_ANGELS",
  "CHANCE_MOVE_ENEMY_ON_ATTACK",
  "CHANCE_TO_PARALYZE",
  "HIGH_CHANCE_TO_PARALYZE",
  "CHANCE_TO_POISON",
  "DOUBLE_ATTACK", 
  "BLOODLUST_ONE", // TODO Not sure if its even smart to use this on itself (lose a turn of damage)
  "BLOODLUST_TWO", // TODO Not sure if its even smart to use this on itself (lose a turn of damage)
  "LIGHTNING",
  "DECREASE_DEFENCE",
  "DECREASE_DEFENCE_AND_CORODE",// TODO corode effect if its known what it does
  "REBIRTH",
  "WEAKNESS_ON_ATTACK", // TODO What does weakness do??
  "LIMIT_DAMAGE_FROM_ATTACK",
  "REVENGE", 
}
